import { createSlice } from '@reduxjs/toolkit'


const initialState = {
  roomId: null,
  titleChannel: null
}

export const appSlice = createSlice({
  name: 'app',
  initialState,

  reducers: {
    enterRoom: (state, action) => {
      state.roomId = action.payload.roomId,
      state.titleChannel = action.payload.titleChannel
    }


    //NEW
  }

  // The `extraReducers` field lets the slice handle actions defined elsewhere,
  // including actions generated by createAsyncThunk or in other slices.
//   extraReducers: (builder) => {}
})


export const { enterRoom } = appSlice.actions

// export const selectRoomId = state => state.app.roomId

export default appSlice.reducer