import { createSlice } from '@reduxjs/toolkit'


const initialState = {
  statusModal: false

}

export const modalSlice = createSlice({
  name: 'modal',
  initialState,

  reducers: {
    closeModal: (state) => {
      state.statusModal = false
    },

    openModal: (state) => {
      state.statusModal = true
    }


    //NEW
  }

  // The `extraReducers` field lets the slice handle actions defined elsewhere,
  // including actions generated by createAsyncThunk or in other slices.
//   extraReducers: (builder) => {}
})


export const { openModal, closeModal } = modalSlice.actions

// export const selectRoomId = state => state.app.roomId

export default modalSlice.reducer